'use client'
import { BadgeCheck, ArrowUpLeft, Filter, PlusCircle, X, Loader2 } from 'lucide-react'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)
export default function Market(){const [filter,setFilter]=useState('همه');const [listings,setListings]=useState<any[]>([]);const [owns,setOwns]=useState<any[]>([]);const [open,setOpen]=useState(false);const [price,setPrice]=useState('');const [qty,setQty]=useState('1');const [ownership,setOwnership]=useState('');const [msg,setMsg]=useState('');const [loading,setLoading]=useState(false)
 async function load(){const c=supabase();if(!c)return;const {data}=await c.from('listings').select('id,price,quantity,status,created_at,products(name,image_url,category)').eq('status','active').order('created_at',{ascending:false});setListings(data||[]);const {data:{user}}=await c.auth.getUser();if(user){const {data:o}=await c.from('ownerships').select('id,quantity,ownership_percent,resale_eligible,products(name)').eq('user_id',user.id).eq('resale_eligible',true);setOwns(o||[])}}
 useEffect(()=>{load()},[])
 async function create(){setMsg('');const c=supabase();if(!c){setMsg('Supabase تنظیم نشده.');return}if(!ownership){setMsg('یک مالکیت واجد شرایط را انتخاب کن.');return}setLoading(true);const {data,error}=await c.rpc('create_listing',{p_ownership_id:ownership,p_price:Number(price),p_quantity:Number(qty)});setMsg(error?`ثبت آگهی انجام نشد: ${error.message}`:`آگهی با کد ${data} ثبت شد.`);if(!error){setOpen(false);setPrice('');setQty('1');load()}setLoading(false)}
 return <main className="page"><div className="page-head"><div><span className="eyebrow">USER MARKETPLACE · LIVE</span><h1>بازار کاربران</h1><p>فقط کالاهایی که مالک آن‌ها در دیتابیس واجد شرایط فروش مجدد شده، وارد این بازار می‌شوند.</p></div><button className="btn primary" onClick={()=>setOpen(true)}><PlusCircle size={16}/> فروش یک کالا</button></div>{msg&&<div className="form-msg top-msg">{msg}</div>}<div className="market-tools"><button className={filter==='همه'?'active':''} onClick={()=>setFilter('همه')}><Filter size={15}/> همه</button><button className={filter==='تاییدشده'?'active':''} onClick={()=>setFilter('تاییدشده')}>مالک تاییدشده</button></div><div className="market-grid">{listings.filter(x=>filter==='همه'||x.status==='active').map((x,i)=><article className="listing" key={x.id}><div className={'listing-art la'+i%4}><ArrowUpLeft size={26}/><span>RESALE</span></div><div className="listing-body"><small>{x.products?.category||'کالا'} · {x.quantity} عدد</small><h3>{x.products?.name||'محصول'}</h3><p><BadgeCheck size={15}/> مالک واجد شرایط</p><strong>{money(Number(x.price))} <small>تومان</small></strong><button className="full-btn" onClick={()=>alert('خرید بازار در مرحله پرداخت و انتقال مالکیت فعال می‌شود.')}>مشاهده کالا</button></div></article>)}{!listings.length&&<div className="empty-card market-empty"><BadgeCheck size={34}/><h2>هنوز آگهی فعالی وجود ندارد</h2><p>وقتی اولین خریدها پرداخت و مالکیتشان واجد شرایط فروش شود، اینجا آگهی‌ها نمایش داده می‌شوند.</p></div>}</div>{open&&<div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={()=>setOpen(false)}><X/></button><span className="eyebrow">CREATE LISTING</span><h2>ثبت فروش کالا</h2><p>این فرم فقط مالکیت‌های واجد شرایط را می‌پذیرد.</p>{owns.length?<><select value={ownership} onChange={e=>setOwnership(e.target.value)}><option value="">انتخاب کالا</option>{owns.map(o=><option key={o.id} value={o.id}>{o.products?.name} · {o.quantity} عدد · {Number(o.ownership_percent).toFixed(2)}٪</option>)}</select><input value={price} onChange={e=>setPrice(e.target.value.replace(/\D/g,''))} placeholder="قیمت فروش به تومان"/><input value={qty} onChange={e=>setQty(e.target.value.replace(/\D/g,'')||'1')} placeholder="تعداد"/><button className="btn primary full" disabled={loading} onClick={create}>{loading?<Loader2 className="spin"/>:'ثبت آگهی'}</button></>:<div className="form-msg">فعلاً مالکیت واجد شرایطی در حساب شما وجود ندارد. بعد از پرداخت و ثبت مالکیت، این قسمت فعال می‌شود.</div>}</div></div>}</main>}
