'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { ShieldCheck, Plus, Save, RefreshCw, Gift, ListChecks, Package, Clock3 } from 'lucide-react'
import { supabase } from '@/lib/supabase'
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)
export default function Admin(){const [allowed,setAllowed]=useState<boolean|null>(null);const [products,setProducts]=useState<any[]>([]);const [tasks,setTasks]=useState<any[]>([]);const [preorders,setPreorders]=useState<any[]>([]);const [gift,setGift]=useState({code:'',points:'100',max:'100'});const [msg,setMsg]=useState('');const [loading,setLoading]=useState(false)
 async function load(){const c=supabase();if(!c){setAllowed(false);return}const {data:{user}}=await c.auth.getUser();if(!user){setAllowed(false);return}const {data:profile}=await c.from('profiles').select('role').eq('id',user.id).single();if(profile?.role!=='admin'){setAllowed(false);return}setAllowed(true);const [{data:p},{data:t},{data:pre}]=await Promise.all([c.from('products').select('*').order('created_at',{ascending:false}),c.from('reward_tasks').select('*').order('created_at'),c.from('preorders').select('*').order('created_at',{ascending:false})]);setProducts(p||[]);setTasks(t||[]);setPreorders(pre||[])}
 useEffect(()=>{load()},[])
 async function saveProduct(p:any){const c=supabase();if(!c)return;setLoading(true);const {error}=await c.from('products').update({price:Number(p.price),status:p.status,updated_at:new Date().toISOString()}).eq('id',p.id);setMsg(error?error.message:'محصول ذخیره شد.');setLoading(false)}
 async function toggleTask(t:any){const c=supabase();if(!c)return;const {error}=await c.from('reward_tasks').update({active:!t.active}).eq('id',t.id);setMsg(error?error.message:'وضعیت تسک تغییر کرد.');load()}
 async function savePre(p:any){const c=supabase();if(!c)return;const {error}=await c.from('preorders').update({status:p.status,ends_at:p.ends_at,unit_price:Number(p.unit_price)}).eq('id',p.id);setMsg(error?error.message:'پیش‌فروش ذخیره شد.');load()}
 async function createGift(){const c=supabase();if(!c)return;const {error}=await c.from('gift_codes').insert({code:gift.code.trim().toUpperCase(),points:Number(gift.points),max_uses:Number(gift.max),active:true});setMsg(error?error.message:'کد هدیه ساخته شد.');if(!error)setGift({code:'',points:'100',max:'100'});}
 if(allowed===null)return <main className="page"><div className="empty-card"><RefreshCw className="spin" size={34}/><h2>در حال بررسی دسترسی مدیر...</h2></div></main>
 if(!allowed)return <main className="page"><div className="empty-card"><ShieldCheck size={40}/><h2>این بخش مخصوص مدیر پروژه است</h2><p>برای فعال‌سازی، بعد از ساخت حساب خودت دستور role=admin داخل seed.sql را با ایمیل خودت اجرا کن.</p><Link href="/dashboard" className="btn ghost">بازگشت</Link></div></main>
 return <main className="page admin-page"><div className="page-head"><div><span className="eyebrow">PROJECT CONTROL · ADMIN</span><h1>مرکز مدیریت</h1><p>مدیریت کاتالوگ، تسک‌ها، کدهای هدیه و وضعیت پیش‌فروش از یک نقطه.</p></div><button className="btn ghost" onClick={load}><RefreshCw size={15}/> بروزرسانی</button></div>{msg&&<div className="form-msg top-msg">{msg}</div>}<section className="admin-grid"><div className="panel"><div className="panel-title"><div><h2><Package size={18}/> محصولات</h2><p>قیمت و وضعیت قابل مدیریت است.</p></div></div>{products.map(p=><div className="admin-row" key={p.id}><div><b>{p.name}</b><small>{p.sku}</small></div><input value={p.price} onChange={e=>setProducts(xs=>xs.map(x=>x.id===p.id?{...x,price:e.target.value}:x))}/><select value={p.status} onChange={e=>setProducts(xs=>xs.map(x=>x.id===p.id?{...x,status:e.target.value}:x))}><option value="active">فعال</option><option value="draft">پیش‌نویس</option><option value="archived">آرشیو</option></select><button className="icon-btn" disabled={loading} onClick={()=>saveProduct(p)}><Save size={15}/></button></div>)}</div><div className="panel"><div className="panel-title"><div><h2><ListChecks size={18}/> تسک‌ها</h2><p>فعال/غیرفعال کردن مرکز امتیاز.</p></div></div>{tasks.map(t=><div className="admin-row" key={t.id}><div><b>{t.title}</b><small>+{money(t.points)} امتیاز</small></div><button className={t.active?'switch on':'switch'} onClick={()=>toggleTask(t)}>{t.active?'فعال':'خاموش'}</button></div>)}</div><div className="panel"><div className="panel-title"><div><h2><Gift size={18}/> کد هدیه</h2><p>ساخت کد جدید با محدودیت استفاده.</p></div></div><div className="gift-admin-form"><input value={gift.code} onChange={e=>setGift({...gift,code:e.target.value})} placeholder="CODE"/><input value={gift.points} onChange={e=>setGift({...gift,points:e.target.value})} placeholder="امتیاز"/><input value={gift.max} onChange={e=>setGift({...gift,max:e.target.value})} placeholder="تعداد استفاده"/><button className="btn primary" onClick={createGift}><Plus size={15}/> ساخت</button></div></div><div className="panel"><div className="panel-title"><div><h2><Clock3 size={18}/> پیش‌فروش‌ها</h2><p>قیمت و وضعیت کمپین را کنترل کن.</p></div></div>{preorders.map(p=><div className="admin-row preorder-admin" key={p.id}><div><b>{p.title}</b><small>{Number(p.reserved_percent).toFixed(2)}٪ رزرو شده · {money(p.unit_price)} تومان</small></div><input value={p.unit_price} onChange={e=>setPreorders(xs=>xs.map(x=>x.id===p.id?{...x,unit_price:e.target.value}:x))}/><select value={p.status} onChange={e=>setPreorders(xs=>xs.map(x=>x.id===p.id?{...x,status:e.target.value}:x))}><option value="open">باز</option><option value="funded">تأمین شد</option><option value="closed">بسته</option><option value="cancelled">لغو</option></select><button className="icon-btn" onClick={()=>savePre(p)}><Save size={15}/></button></div>)}</div></section></main>}
