'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Gift, Camera, PlayCircle, Send, Users, CheckCircle2, ArrowLeft, Loader2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Task={id:string;slug:string;title:string;description:string;points:number}
const icons:any={watch_ad:PlayCircle,referral:Users,instagram_follow:Camera,telegram_join:Send}
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)
export default function Tasks(){const [tasks,setTasks]=useState<Task[]>([]);const [done,setDone]=useState<string[]>([]);const [points,setPoints]=useState(0);const [referral,setReferral]=useState('—');const [gift,setGift]=useState('');const [giftMsg,setGiftMsg]=useState('');const [loading,setLoading]=useState<string|null>(null);const [pageMsg,setPageMsg]=useState('')
 useEffect(()=>{(async()=>{const c=supabase();if(!c)return;const {data:{user}}=await c.auth.getUser();const {data:ts}=await c.from('reward_tasks').select('id,slug,title,description,points').eq('active',true).order('created_at');setTasks((ts||[]) as Task[]);if(user){const [{data:p},{data:u}]=await Promise.all([c.from('profiles').select('reward_points,referral_code').eq('id',user.id).single(),c.from('user_reward_tasks').select('task_id').eq('user_id',user.id)]);setPoints(p?.reward_points||0);setReferral(p?.referral_code||'—');setDone((u||[]).map((x:any)=>x.task_id))}})()},[])
 async function complete(task:Task){setLoading(task.id);setPageMsg('');const c=supabase();if(!c){setPageMsg('اتصال Supabase تنظیم نشده است.');setLoading(null);return}const {data:{user}}=await c.auth.getUser();if(!user){setPageMsg('برای دریافت امتیاز باید وارد حساب شوی.');setLoading(null);return}const {data,error}=await c.rpc('claim_reward_task',{p_task_id:task.id});if(error){setPageMsg(error.message.includes('TASK_ALREADY_CLAIMED')?'این تسک قبلاً ثبت شده است.':error.message.includes('AUTH_REQUIRED')?'ابتدا وارد حساب شو.':'ثبت تسک انجام نشد.')}else{setDone(x=>[...x,task.id]);setPoints(data?.new_total||points+task.points);setPageMsg(`+${money(task.points)} امتیاز به حساب اضافه شد.`)}setLoading(null)}
 async function redeem(){setGiftMsg('');const c=supabase();if(!c){setGiftMsg('اتصال Supabase تنظیم نشده است.');return}const {data,error}=await c.rpc('redeem_gift_code',{p_code:gift});if(error){const map:any={INVALID_GIFT_CODE:'کد معتبر نیست.',GIFT_EXPIRED:'کد منقضی شده است.',GIFT_LIMIT_REACHED:'ظرفیت این کد تکمیل شده است.',GIFT_ALREADY_USED:'این کد قبلاً توسط شما استفاده شده است.',AUTH_REQUIRED:'ابتدا وارد حساب شو.'};setGiftMsg(map[error.message]||'ثبت کد انجام نشد.')}else{setPoints(data?.new_total||points);setGiftMsg(`کد با موفقیت ثبت شد؛ ${money(data?.points||0)} امتیاز گرفتی.`);setGift('')}}
 return <main className="page"><div className="page-head"><div><span className="eyebrow">REWARD CENTER · LIVE DATABASE</span><h1>تسک‌ها و امتیازها</h1><p>تسک‌ها و کدهای هدیه این نسخه دیگر فقط نمایشی نیستند؛ ثبت امتیاز با تابع امن Supabase انجام می‌شود.</p></div><div className="points-badge"><small>امتیاز من</small><strong>{money(points)}</strong></div></div>{pageMsg&&<div className="form-msg top-msg">{pageMsg}</div>}<section className="ref-card"><div><small>کد معرف من</small><strong>{referral}</strong><p>کد معرف برای هر حساب از دیتابیس ساخته می‌شود.</p></div><button className="btn primary" disabled={referral==='—'} onClick={()=>navigator.clipboard?.writeText(referral)}>کپی کد</button></section><div className="tasks-grid">{tasks.map(t=>{const Icon=icons[t.slug]||CheckCircle2;const ok=done.includes(t.id);return <article className="task-card" key={t.id}><div className="task-icon"><Icon/></div><div><span>+{money(t.points)} امتیاز</span><h3>{t.title}</h3><p>{t.description}</p></div><button className="btn ghost" disabled={ok||loading===t.id} onClick={()=>complete(t)}>{loading===t.id?<Loader2 className="spin" size={16}/>:ok?<><CheckCircle2 size={16}/> ثبت شده</>:<>ثبت انجام <ArrowLeft size={15}/></>}</button></article>})}</div><section className="gift-card"><div className="gift-icon"><Gift/></div><div><span className="eyebrow">GIFT CODE</span><h2>کد هدیه داری؟</h2><p>کدهایی که از طرف پروژه منتشر می‌شوند اینجا یک‌بار برای هر حساب قابل استفاده‌اند.</p><div className="gift-form"><input value={gift} onChange={e=>setGift(e.target.value)} placeholder="مثلاً WELCOME100"/><button className="btn primary" onClick={redeem}>ثبت کد</button></div>{giftMsg&&<small className="form-msg">{giftMsg}</small>}</div></section><Link href="/dashboard" className="btn ghost">بازگشت به داشبورد</Link></main>}
