'use client'
import { useEffect,useMemo,useState } from 'react'
import { Clock3, Users, ShieldCheck, ArrowLeft, Percent, Target, Loader2, Database } from 'lucide-react'
import { supabase } from '@/lib/supabase'
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)
function Timer({ends}:{ends:string|null}){const [s,setS]=useState(0);useEffect(()=>{const tick=()=>setS(Math.max(0,Math.floor(((ends?new Date(ends).getTime():Date.now())-Date.now())/1000)));tick();const t=setInterval(tick,1000);return()=>clearInterval(t)},[ends]);const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;return <>{d} روز · {String(h).padStart(2,'0')}:{String(m).padStart(2,'0')}:{String(sec).padStart(2,'0')}</>}
export default function Preorders(){const [p,setP]=useState<any>(null);const [percent,setPercent]=useState(1);const [myPercent,setMyPercent]=useState(0);const [myAmount,setMyAmount]=useState(0);const [msg,setMsg]=useState('');const [loading,setLoading]=useState(false)
 useEffect(()=>{let channel:any;(async()=>{const c=supabase();if(!c)return;const {data}=await c.from('preorders').select('*').eq('status','open').order('created_at').limit(1).maybeSingle();setP(data);const {data:{user}}=await c.auth.getUser();if(data&&user){const {data:mine}=await c.from('preorder_investments').select('percent,amount').eq('preorder_id',data.id).eq('user_id',user.id).maybeSingle();setMyPercent(mine?.percent||0);setMyAmount(mine?.amount||0)}if(data){channel=c.channel('preorder-live').on('postgres_changes',{event:'UPDATE',schema:'public',table:'preorders',filter:`id=eq.${data.id}`},(payload:any)=>setP(payload.new)).subscribe()}})();return()=>{if(channel)supabase()?.removeChannel(channel)}} ,[])
 const unit=p?.unit_price||6680000,total=p?.total_target||250*6680000;const ownership=percent;const invest=Math.round(total*percent/100);const progress=Number(p?.reserved_percent||0);const remaining=Math.max(0,100-progress);const maxForUser=Math.min(100,remaining+myPercent);const effectivePercent=Math.min(percent,maxForUser);const effectiveInvest=Math.round(total*effectivePercent/100)
 async function reserve(){setMsg('');const c=supabase();if(!c){setMsg('اتصال Supabase تنظیم نشده است.');return}const {data:{user}}=await c.auth.getUser();if(!user){setMsg('برای ثبت سهم ابتدا وارد حساب شو.');return}setLoading(true);const {data,error}=await c.rpc('reserve_preorder_share',{p_preorder_id:p.id,p_percent:effectivePercent});if(error){const map:any={PREORDER_CAP_REACHED:'ظرفیت کل پیش‌فروش پر شده است.',PREORDER_ENDED:'زمان پیش‌فروش تمام شده است.',AUTH_REQUIRED:'ابتدا وارد حساب شو.'};setMsg(map[error.message]||'ثبت سهم انجام نشد.')}else{setMyPercent(data.percent);setMyAmount(data.amount);setMsg(`سهم شما در دیتابیس ثبت شد: ${Number(data.percent).toFixed(2)}٪. مبلغ ${money(data.amount)} تومان فعلاً «تعهد ثبت‌شده» است و پرداخت واقعی هنوز فعال نشده.`)}setLoading(false)}
 if(!p)return <main className="page"><div className="empty-card"><Database size={38}/><h2>در حال دریافت پیش‌فروش از Supabase...</h2><p>اگر چیزی نمایش داده نشد، seed.sql را اجرا کن.</p></div></main>
 return <main className="page"><div className="page-head"><div><span className="eyebrow">LIMITED PREORDER · PAGEELA · LIVE</span><h1>پیش‌فروش مشارکتی</h1><p>سهم هر کاربر در دیتابیس ثبت می‌شود و درصد تأمین پروژه به‌صورت زنده قابل مشاهده است.</p></div><div className="pill">هدف تولید: {money(p.target_qty)} عدد</div></div><article className="pre-card preorder-pageela"><div className="pre-art photo-art"><img src={p.product_id?'/products/pageela-preorder.svg':'/products/pageela-preorder.svg'} alt="دورس مشکی PAGEELA"/></div><div className="pre-body"><span className="status-live">● PREORDER LIVE · REAL SUPABASE DATA</span><h2>{p.title}</h2><p>دورس مشکی ۴ نخ پنبه خارخورده درجه یک با آرم PAGEELA گلدوزی‌شده روی سینه. در این مرحله سهم شما به‌عنوان رزرو مشارکت ثبت می‌شود؛ پرداخت واقعی، تولید، ارسال و بازار ثانویه در مرحله مالی امن پروژه فعال خواهند شد.</p><div className="pre-metrics"><div><Target size={18}/><b>{money(p.target_qty)} عدد</b><small>هدف تولید</small></div><div><Users size={18}/><b>{progress.toFixed(2)}٪</b><small>درصد رزرو شده</small></div><div><Clock3 size={18}/><b><Timer ends={p.ends_at}/></b><small>زمان باقی‌مانده</small></div></div><div className="progress"><i style={{width:`${Math.min(100,progress)}%`}}/></div><div className="investment-box"><div><small>ارزش هر دورس</small><strong>{money(unit)} تومان</strong></div><div><small>ارزش کل ۲۵۰ عدد</small><strong>{money(total)} تومان</strong></div></div><div className="percent-control"><div className="percent-title"><span><Percent size={16}/> سهم مورد نظر</span><b>{ownership}٪</b></div><input type="range" min="1" max={Math.max(1,Math.floor(maxForUser))} step="1" value={Math.min(percent,Math.floor(maxForUser))} onChange={e=>setPercent(Number(e.target.value))}/><div className="percent-help"><span>۱٪ = {money(Math.round(total/100))} تومان</span><strong>{money(invest)} تومان</strong></div></div><div className="pre-note"><ShieldCheck size={17}/> سهم شما: <b>{myPercent.toFixed(2)}٪</b> · ارزش ثبت‌شده: <b>{money(myAmount)} تومان</b>. این عدد هنوز موجودی کیف پول یا پرداخت قطعی نیست.</div>{msg&&<div className="form-msg top-msg">{msg}</div>}<div className="pre-footer"><strong>{money(effectiveInvest)} تومان</strong><button className="btn primary" disabled={loading} onClick={reserve}>{loading?<Loader2 className="spin" size={16}/>:<>ثبت سهم در حساب <ArrowLeft size={16}/></>}</button></div></div></article></main>}
