'use client'
import { useEffect,useState } from 'react'
import { supabase,hasSupabaseEnv } from '@/lib/supabase'
import { Box, Coins, PackageCheck, UserRound, LogIn, ArrowLeft, ListChecks, Percent, ShoppingBag, RefreshCw } from 'lucide-react'
import Link from 'next/link'
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(n)
export default function Dashboard(){const [email,setEmail]=useState('در حال بررسی...');const [points,setPoints]=useState(0);const [share,setShare]=useState(0);const [wallet,setWallet]=useState(0);const [orders,setOrders]=useState(0);const [eligible,setEligible]=useState(0);const [ref,setRef]=useState('—');const [refresh,setRefresh]=useState(false)
 async function load(){setRefresh(true);const c=supabase();if(!c){setEmail('اتصال Supabase تنظیم نشده');setRefresh(false);return}const {data:{user}}=await c.auth.getUser();if(!user){setEmail('وارد نشده‌اید');setRefresh(false);return}setEmail(user.email||'کاربر');const [{data:p},{data:inv},{data:led,count:orderCount},{data:os},{data:own,count:eligibleCount}]=await Promise.all([c.from('profiles').select('reward_points,referral_code').eq('id',user.id).single(),c.from('preorder_investments').select('percent').eq('user_id',user.id).in('status',['reserved','paid','converted']),c.from('wallet_ledger').select('amount').eq('user_id',user.id),c.from('orders').select('id',{count:'exact',head:true}).eq('user_id',user.id),c.from('ownerships').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('resale_eligible',true)]);setPoints(p?.reward_points||0);setRef(p?.referral_code||'—');setShare((inv||[]).reduce((s:any,x:any)=>s+Number(x.percent||0),0));setWallet((led||[]).reduce((s:any,x:any)=>s+Number(x.amount||0),0));setOrders(orderCount||0);setEligible(eligibleCount||0);setRefresh(false)}
 useEffect(()=>{load()},[])
 return <main className="page"><div className="dash-head"><div><span className="eyebrow">MY KOLBE · LIVE ACCOUNT</span><h1>داشبورد من</h1><p>{email}</p></div><div className="dash-actions"><button className="btn ghost" onClick={load}><RefreshCw size={15} className={refresh?'spin':''}/> بروزرسانی</button><div className="avatar"><UserRound/></div></div></div>{!hasSupabaseEnv()&&<div className="setup-warning"><b>اتصال Supabase</b><span>URL پروژه را در <code>.env.local</code> بگذار.</span><Link href="/auth/login">ورود <ArrowLeft size={15}/></Link></div>}<div className="stats-grid"><div><Coins/><small>موجودی کیف پول</small><strong>{money(wallet)} تومان</strong></div><div><ListChecks/><small>امتیازها</small><strong>{money(points)} امتیاز</strong></div><div><Percent/><small>سهم پیش‌خرید من</small><strong>{share.toFixed(2)}٪</strong></div><div><Box/><small>کالاهای قابل فروش</small><strong>{money(eligible)} کالا</strong></div></div><section className="account-strip"><div><ShoppingBag/><span><b>{money(orders)}</b><small>سفارش ثبت‌شده</small></span></div><div><UserRound/><span><b>{ref}</b><small>کد معرف من</small></span></div><Link href="/tasks">مرکز امتیازها <ArrowLeft size={15}/></Link></section><section className="panel"><div className="panel-title"><div><h2>ساختمان پروژه</h2><p>هر طبقه یک موتور واقعی از کسب‌وکار پروژه است.</p></div><span>05 / 06</span></div><div className="building-row">{['STORE','PREORDER','MARKET','WALLET','REWARDS','NEXT'].map((x,i)=><div className={i===5?'locked':''} key={x}><b>۰{i+1}</b><strong>{x}</strong><small>{i===5?'در حال ساخت':'ACTIVE'}</small></div>)}</div></section><div className="quick-links"><Link href="/store"><PackageCheck/><span>خرید محصول</span></Link><Link href="/preorders"><Percent/><span>پیش‌خرید درصدی</span></Link><Link href="/tasks"><ListChecks/><span>تسک‌ها</span></Link><Link href="/wallet"><Coins/><span>گردش حساب</span></Link><Link href="/market"><Box/><span>بازار کاربران</span></Link></div></main>}
